name: Patch and Build

on:
  push:

jobs:
  compile_1_21_4_core_jar:
    runs-on: windows-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Build
        run: ./gradlew clean build
           
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: Eco
          path: "*"
